### ISSUE TITLE
Corresponding versions for OMOP 5.4.0

### ISSUE THREAD

**Issue by eduard93** [OHDSI/OHDSIonAWS#17]
Assuming I wan to to use OMOP version 5.4.0 (or 5.4.1), what are the recommended versions for other packages?

```yaml
OMOPv:
    Description: The OHDSI CommonDataModel GitHub branch you want deployed (this specifies the version)
    Type: String
    Default: '5.3.0'
  Atlasv:
    Description: The OHDSI Atlas GitHub branch you want deployed (this specifies the version)
    Type: String
    Default: '2.12.0'
  WebAPIv:
    Description: OHDSI WebAPI GitHub branch you want deployed (this specifies the version)
    Type: String
    Default: '2.12.0'
  Achillesv:
    Description: OHDSI Achilles GitHub branch you want deployed (this specifies the version)
    Type: String
    Default: '1.6.3'
  PatientLevelPredictionv:
    Description: OHDSI PatientLevelPrediction GitHub branch you want deployed (this specifies the version)
    Type: String
    Default: '5.0.5'
  CohortMethodv:
    Description: OHDSI CohortMethod GitHub branch you want deployed (this specifies the version)
    Type: String
    Default: '4.2.3'
  SqlRenderv:
    Description: OHDSI SqlRender GitHub branch you want deployed (this specifies the version)
    Type: String
    Default: '1.9.2'
  DatabaseConnectorv:
    Description: OHDSI DatabaseConnector GitHub branch you want deployed (this specifies the version)
    Type: String
    Default: '5.0.0'
  DatabaseConnectorJarsv:
    Description: OHDSI DatabaseConnectorJars GitHub branch you want deployed (this specifies the version)
    Type: String
    Default: '1.1.0'
  OhdsiRToolsv:
    Description: OhdsiRTools GitHub branch you want deployed (this specifies the version)
    Type: String
    Default: '2.0.2'
  FeatureExtractionv:
    Description: OHDSI FeatureExtraction GitHub branch you want deployed (this specifies the version)
    Type: String
    Default: '3.2.0'
  Cyclopsv:
    Description: OHDSI Cyclops GitHub branch you want deployed (this specifies the version)
    Type: String
    Default: '3.2.0'
  EmpiricalCalibrationv:
    Description: OHDSI EmpiricalCalibration GitHub branch you want deployed (this specifies the version)
    Type: String
    Default: '3.1.1'
  OhdsiSharingv:
    Description: OHDSI OhdsiSharing GitHub branch you want deployed (this specifies the version)
    Type: String
    Default: '0.2.2'
  MethodEvaluationv:
    Description: OHDSI MethodEvaluation GitHub branch you want deployed (this specifies the version)
    Type: String
    Default: '2.2.0'
  Hydrav:
    Description: OHDSI Hydra GitHub branch you want deployed (this specifies the version)
    Type: String
    Default: '0.3.0'
  PredictionComparisonv:
    Description: OHDSI Hydra GitHub branch you want deployed (this specifies the version)
    Type: String
    Default: '0.1.0'
  Eunomiav:
    Description: OHDSI Eunomia GitHub branch you want deployed (this specifies the version)
    Type: String
    Default: '1.0.2'
  Andromedav:
    Description: OHDSI Andromeda GitHub branch you want deployed (this specifies the version)
    Type: String
    Default: '0.6.1'
  BigKNNv:
    Description: OHDSI Andromeda GitHub branch you want deployed (this specifies the version)
    Type: String
    Default: '1.0.1'
  SelfControlledCaseSeriesv:
    Description: OHDSI SelfControlledCaseSeries GitHub branch you want deployed (this specifies the version)
    Type: String
    Default: '3.4.0'
  SelfControlledCohortv:
    Description: OHDSI SelfControlledCohort GitHub branch you want deployed (this specifies the version)
    Type: String
    Default: '1.6.0'
  EvidenceSynthesisv:
    Description: OHDSI EvidenceSynthesis GitHub branch you want deployed (this specifies the version)
    Type: String
    Default: '0.3.0'
  CohortDiagnosticsv:
    Description: OHDSI CohortDiagnostics GitHub branch you want deployed (this specifies the version)
    Type: String
    Default: '3.0.3'
  Hadesv:
    Description: OHDSI Hades GitHub branch you want deployed (this specifies the version)
    Type: String
    Default: '1.3.0'
```
